FROM nvidia/cuda:12.3.2-runtime-ubuntu22.04

RUN apt update
RUN apt upgrade -y
RUN apt update
RUN apt install -y curl ca-certificates git zsh wget vim gcc-12 g++-12 make cmake ninja-build clang-14 openssh-server

# Use update alternatives to set gcc-12 and g++-12 as default
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 512
RUN update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 512

RUN mkdir /workspace
WORKDIR /workspace

# Zsh
RUN wget -O /etc/zsh/zshrc https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc
RUN chsh -s /bin/zsh

# Install miniconda
RUN wget -O miniconda.sh https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh && \
    chmod +x miniconda.sh && \
    ./miniconda.sh -b -p /opt/conda && \
    rm miniconda.sh

ENV PATH="/opt/conda/bin:${PATH}"

# Misc
# If you mount a git repo to /workspace, git will complain without this
RUN git config --global --add safe.directory /workspace
ENV USER=haydnj

# Clean up
RUN mamba clean -qya
RUN pip cache purge
RUN rm -rf /workspace/*
RUN apt autoremove -y
RUN apt autoclean -y


ENTRYPOINT [ "/bin/zsh" ]