FROM nvidia/cuda:12.5.1-devel-ubuntu24.04

# Install runtime dependencies
RUN apt update && apt install -y \
    curl wget htop tmux \
    ca-certificates locales \
    git git-core gnupg zsh vim sudo && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

# Generate locale
RUN locale-gen en_US.UTF-8

# Set up UV
ENV CARGO_HOME="/opt/cargo"
ENV PATH="/opt/cargo/bin:$PATH"
ENV UV_NO_CACHE=1
ENV UV_COMPILE_BYTECODE=1

ADD https://astral.sh/uv/install.sh /uv-installer.sh
RUN sh /uv-installer.sh && rm /uv-installer.sh

# Create venv
RUN uv venv /opt/venv
ENV VIRTUAL_ENV=/opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN chmod -R 777 /opt /root
RUN chmod +t /opt /root

RUN mkdir /workspace
WORKDIR /workspace

RUN chsh -s /bin/zsh
ARG ZSHRC_PATH=/etc/zsh/zshrc
RUN wget -O ${ZSHRC_PATH} https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc

# Misc
RUN git config --global --add safe.directory /workspace

# Huggingface home
RUN mkdir /huggingface
ENV HF_HOME=/huggingface

RUN mkdir -p /home/runai-home
RUN ln -s ${ZSHRC_PATH} /home/runai-home/.zshrc

ENTRYPOINT [ "/bin/zsh" ]