FROM nvidia/cuda:12.6.3-cudnn-runtime-ubuntu24.04

ENV UV_NO_CACHE=1 \
    UV_COMPILE_BYTECODE=1 \
    VIRTUAL_ENV="/home/haydnj/venv" \
    UV_PROJECT_ENVIRONMENT="/home/haydnj/venv" \
    ZDOTDIR="/etc/zsh" \
    HF_HOME="/huggingface"

# Create user / group haydnj with UID/GID 67761
RUN groupadd -g 67761 haydnj \
    && useradd -m -u 67761 -g 67761 haydnj

# Install dependencies and set up the environment
RUN apt update && apt install -y --no-install-recommends \
    curl wget htop tmux acl openssh-server openssh-client \
    ca-certificates git git-core gnupg zsh git \
    vim sudo build-essential gcc g++ clang ninja-build \
    && apt clean \
    && rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*

# Get zellij
RUN wget https://github.com/zellij-org/zellij/releases/download/v0.41.2/zellij-x86_64-unknown-linux-musl.tar.gz -O /tmp/zellij.tar.gz \
    && tar -xvf /tmp/zellij.tar.gz -C /tmp \
    && mv /tmp/zellij /bin/zellij \
    && chmod +x /bin/zellij

COPY --from=ghcr.io/astral-sh/uv:0.5.6 /uv /uvx /bin/

RUN mkdir -p /workspace /huggingface \
    && git config --global --add safe.directory /workspace

RUN chown -R haydnj:haydnj /workspace

# Set up ZSH
RUN chsh -s /bin/zsh \
    && wget -O /etc/zsh/.zshrc https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc \
    && echo "source /home/haydnj/venv/bin/activate" >> /etc/zsh/.zshrc

RUN setfacl -d -R -m u::rwX,g::rwX,o::rwX /etc/zsh /workspace
RUN chmod -R ugo=rwX /etc/zsh /workspace

USER haydnj
ENV USER=haydn

RUN uv python install 3.12 3.11 3.10 3.9 3.8
RUN uv venv --python 3.12 $VIRTUAL_ENV

WORKDIR /workspace
RUN rm -rf /workspace/*

CMD ["/bin/zsh"]