FROM runpod/base:0.6.2-cuda12.2.0

# Install miniconda
RUN wget -O miniconda.sh https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh && \
    chmod +x miniconda.sh && \
    ./miniconda.sh -b -p /opt/conda && \
    rm miniconda.sh

ENV PATH="/opt/conda/bin:${PATH}"

# Install torch then jax because torch messes with numpy
RUN mamba install pytorch torchvision torchaudio cpuonly -qy -c pytorch
RUN pip install "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
RUN pip install -U --pre jax -f https://storage.googleapis.com/jax-releases/jax_nightly_releases.html
RUN pip install -U --pre jaxlib -f https://storage.googleapis.com/jax-releases/jaxlib_nightly_cuda12_releases.html

RUN pip install orbax optax jaxtyping flax lightning wandb fire tokenizers datasets selfies fcd distrax einops hf_transfer

RUN git config --global --add safe.directory /workspace

RUN mamba clean -qya
RUN pip cache purge