FROM haydnj/ml_base

RUN pip install "jax[cuda11_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
RUN micromamba install pytorch torchvision torchaudio cpuonly -qy -c pytorch

RUN pip install orbax optax jaxtyping

RUN micromamba clean -qya
RUN pip cache purge
