FROM haydnj/ml_base:latest

# Install torch then jax because torch messes with numpy
RUN mamba install pytorch torchvision torchaudio cpuonly -qy -c pytorch
RUN pip install "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

RUN mamba install -qy matplotlib pandas rdkit tqdm joblib rich rdkit

RUN pip install orbax optax jaxtyping
RUN pip install git+https://github.com/google/flax.git

RUN pip install lightning wandb fire
RUN pip install tokenizers datasets selfies

RUN mamba clean -qya
RUN pip cache purge
