FROM haydnj/ml_base:latest

RUN uv pip install \
    torch==2.6.0+cu124 \
    botorch \
    datasets \
    einops \
    fcd \
    fire \
    git+https://github.com/haydn-jones/guacamol \
    gpytorch \
    hf_transfer \
    hnn-utils \
    ipython \
    joblib \
    lightning \
    matplotlib \
    more_itertools \
    pandas \
    polars \
    pyarrow \
    rich \
    schedulefree \
    selfies \
    tqdm \
    wandb \
    --extra-index-url https://download.pytorch.org/whl/cu124

# Give group read/write access to every file in the venv
RUN chmod 2775 /researchers/venv \
    && chown -R root:researchers /researchers/venv \
    && find /researchers/venv -type d -exec chmod 2775 {} \; \
    && find /researchers/venv -type f -exec chmod 0664 {} \;