FROM haydnj/ml_base:latest

RUN mamba install -qy pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
RUN mamba install -qy matplotlib pandas numpy rdkit tqdm joblib rich rdkit

# Python packages
RUN pip install hnn-utils

RUN pip install botorch gpytorch scipy lightning wandb fire hnn-utils einops
RUN pip install transformers tokenizers datasets selfies guacamol fcd

RUN mamba clean -qya
RUN pip cache purge