FROM runpod/base:0.6.2-cuda12.6.2

ENV UV_COMPILE_BYTECODE=1 \
    VIRTUAL_ENV="/workspace/venv" \
    UV_PROJECT_ENVIRONMENT="/workspace/venv" \
    ZDOTDIR="/etc/zsh" \
    HF_HOME="/workspace/huggingface"

ENV PATH="${VIRTUAL_ENV}/bin:${PATH}"

RUN apt update && apt install -y --no-install-recommends \
    curl wget htop tmux openssh-server openssh-client \
    ca-certificates git git-core gnupg zsh git \
    vim sudo build-essential gcc g++ clang ninja-build \
    && apt clean \
    && rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*

# Get zellij
RUN wget https://github.com/zellij-org/zellij/releases/download/v0.41.2/zellij-x86_64-unknown-linux-musl.tar.gz -O /tmp/zellij.tar.gz \
    && tar -xvf /tmp/zellij.tar.gz -C /tmp \
    && mv /tmp/zellij /bin/zellij \
    && chmod +x /bin/zellij

RUN mkdir -p /workspace ${VIRTUAL_ENV} ${HF_HOME}  \
    && git config --global --add safe.directory /workspace

# Set up ZSH
RUN chsh -s /bin/zsh \
    && wget -O /etc/zsh/.zshrc https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc \
    && echo "source ${VIRTUAL_ENV}/bin/activate" >> /etc/zsh/.zshrc

USER brewuser
RUN brew upgrade uv
USER root

RUN uv python install 3.12 3.11 3.10 3.9 3.8
RUN uv venv --python 3.12 $VIRTUAL_ENV --seed

WORKDIR /workspace/workspace