FROM runpod/base:0.6.3-cuda12.6.2

ENV UV_COMPILE_BYTECODE=1 \
    UV_NO_CACHE=1 \
    VIRTUAL_ENV="/data/venv" \
    UV_PROJECT_ENVIRONMENT="/data/venv" \
    ZDOTDIR="/etc/zsh" \
    HF_HOME="/data/huggingface"

ENV PATH="${VIRTUAL_ENV}/bin:${PATH}"

RUN apt update && apt install -y --no-install-recommends \
    curl wget htop tmux openssh-server openssh-client \
    ca-certificates git git-core gnupg zsh git \
    vim sudo build-essential gcc g++ clang ninja-build \
    && apt clean \
    && rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*

RUN (type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
    && sudo mkdir -p -m 755 /etc/apt/keyrings \
    && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
    && cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
    && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
    && sudo apt update \
    && sudo apt install gh -y

# Get zellij
RUN wget https://github.com/zellij-org/zellij/releases/download/v0.41.2/zellij-x86_64-unknown-linux-musl.tar.gz -O /tmp/zellij.tar.gz \
    && tar -xvf /tmp/zellij.tar.gz -C /tmp \
    && mv /tmp/zellij /bin/zellij \
    && chmod +x /bin/zellij

RUN mkdir -p /workspace ${VIRTUAL_ENV} ${HF_HOME}  \
    && git config --global --add safe.directory /workspace

# Set up ZSH
RUN chsh -s /bin/zsh \
    && wget -O /etc/zsh/zshrc https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc \
    && echo "source ${VIRTUAL_ENV}/bin/activate" >> /etc/zsh/zshrc

USER brewuser
RUN brew upgrade uv
USER root

RUN uv python install 3.12 3.11 3.10
RUN uv venv --python 3.12 $VIRTUAL_ENV --seed
RUN source ${VIRTUAL_ENV}/bin/activate

RUN uv pip install \
    torch==2.7.0+cu126 \
    botorch \
    datasets \
    einops \
    fcd \
    fire \
    gpytorch \
    hf_transfer \
    hnn-utils \
    ipython \
    joblib \
    lightning \
    matplotlib \
    more_itertools \
    pandas \
    polars \
    pyarrow \
    rich \
    selfies \
    tqdm \
    wandb \
    --extra-index-url https://download.pytorch.org/whl/cu126

# Install rust
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y \
    && echo "UV_PROJECT_ENVIRONMENT=${VIRTUAL_ENV}" >> /etc/zsh/zshrc \
    && echo "source ${HOME}/.cargo/env" >> /etc/zsh/zshrc

WORKDIR /workspace/workspace