FROM nvcr.io/nvidia/pytorch:24.02-py3

WORKDIR /workspace

# Misc
# If you mount a git repo to /workspace, git will complain without this
RUN git config --global --add safe.directory /workspace
ENV USER=haydnj

RUN apt autoremove -y
RUN apt autoclean -y

RUN pip install \
    datasets \
    einops \
    fcd \
    fire \
    gpytorch \
    guacamol \
    hnn-utils \
    hnn_utils \
    joblib \
    lightning \
    matplotlib \
    numpy \
    pandas \
    rdkit \
    rdkit \
    rich \
    scipy \
    selfies \
    tokenizers \
    tqdm \
    transformers \
    wandb

RUN rm -rf /workspace/*
