FROM haydnj/ml_base:latest

RUN mamba install -qy pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch-nightly -c nvidia

RUN pip install \
    botorch \
    datasets \
    einops \
    fcd \
    fire \
    gpytorch \
    guacamol \
    hf_transfer \
    hnn-utils \
    ipython \
    joblib \
    lightning \
    matplotlib \
    pandas \
    rich \
    selfies \
    tokenizers \
    tqdm \
    transformers \
    wandb

RUN mamba clean -qya
RUN pip cache purge