name: Build all docker images and publish to Docker Hub

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

  build-base:
    uses: haydn-jones/hnn_utils/.github/workflows/ml_base-docker-publish.yml@main
  build-jax:
    uses: haydn-jones/hnn_utils/.github/workflows/jax-docker-publish.yml@main
  build-torch:
    uses: haydn-jones/hnn_utils/.github/workflows/torch-docker-publish.yml@main
