name: Build and Publish All Docker Images

on:
  workflow_dispatch:

jobs:
  build-base:
    uses: ./.github/workflows/docker_build_template.yml
    with:
      image_name: haydnj/ml_base
      tag: latest
      build_directory: ./docker/base
    secrets: inherit

  build-jax:
    uses: ./.github/workflows/docker_build_template.yml
    needs: build-base
    with:
      image_name: haydnj/jax
      tag: latest
      build_directory: ./docker/jax
    secrets: inherit

  build-torch:
    uses: ./.github/workflows/docker_build_template.yml
    needs: build-base
    with:
      image_name: haydnj/torch
      tag: latest
      build_directory: ./docker/torch
    secrets: inherit
