name: Build all docker images and publish to Docker Hub

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: build-base
        uses: haydn-jones/hnn_utils/.github/workflows/ml_base-docker-publish.yml@main

      - name: build-jax
        uses: haydn-jones/hnn_utils/.github/workflows/jax-docker-publish.yml@main

      - name: build-torch
        uses: haydn-jones/hnn_utils/.github/workflows/torch-docker-publish.yml@main
